GET http://localhost:3003/api/blogs


###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user1",
  "password": "Password123!",
  "name": "User One"
}


###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password123!"
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{$dotenv USERONE_TOKEN}}

{
  "title": "Title One",
  "author": "User One",
  "url": "http://example.com/blog"
}


###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user2",
  "password": "Password123!",
  "name": "User Two"
}


###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password123!"
}


###
# try to delete as user2 (expect 'no permission')
DELETE  http://localhost:3003/api/blogs/6a10b9fd03eaf312361ebfbe
Content-Type: application/json
Authorization: Bearer {{$dotenv USERTWO_TOKEN}}


###
# try to delete as user1 (expect success)
DELETE  http://localhost:3003/api/blogs/6a10b9fd03eaf312361ebfbe
Content-Type: application/json
Authorization: Bearer {{$dotenv USERONE_TOKEN}}
